language: swift
os: osx
osx_image: xcode9.4
before_script:
- gem install xcpretty
- brew install vapor/tap/vapor
script:
- vapor xcode -y
- set -o pipefail && xcodebuild -scheme S3DemoRun clean build | xcpretty